// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-J0mJX3SbTw2rw2UbGm3vO5qpcD-LRo',
    appId: '1:264969234791:web:02f7255243154761e267c2',
    messagingSenderId: '264969234791',
    projectId: 'card-scanner-d8d50',
    authDomain: 'card-scanner-d8d50.firebaseapp.com',
    storageBucket: 'card-scanner-d8d50.firebasestorage.app',
    measurementId: 'G-477DHMXBHK',
    databaseURL: 'https://card-scanner-d8d50-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgP1CQUqCnPblCVv7BtsdEbpyC-ojbhmM',
    appId: '1:264969234791:android:baa79771d4875495e267c2',
    messagingSenderId: '264969234791',
    projectId: 'card-scanner-d8d50',
    storageBucket: 'card-scanner-d8d50.firebasestorage.app',
    databaseURL: 'https://card-scanner-d8d50-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA92eP1bq9gdY50RGFaGLTsEKQgklSpQP0',
    appId: '1:264969234791:ios:8574cc544d66b65de267c2',
    messagingSenderId: '264969234791',
    projectId: 'card-scanner-d8d50',
    storageBucket: 'card-scanner-d8d50.firebasestorage.app',
    databaseURL: 'https://card-scanner-d8d50-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.cardScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA92eP1bq9gdY50RGFaGLTsEKQgklSpQP0',
    appId: '1:264969234791:ios:8574cc544d66b65de267c2',
    messagingSenderId: '264969234791',
    projectId: 'card-scanner-d8d50',
    storageBucket: 'card-scanner-d8d50.firebasestorage.app',
    databaseURL: 'https://card-scanner-d8d50-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.cardScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-J0mJX3SbTw2rw2UbGm3vO5qpcD-LRo',
    appId: '1:264969234791:web:35575a0d9d137f83e267c2',
    messagingSenderId: '264969234791',
    projectId: 'card-scanner-d8d50',
    authDomain: 'card-scanner-d8d50.firebaseapp.com',
    storageBucket: 'card-scanner-d8d50.firebasestorage.app',
    measurementId: 'G-3TGN4SPG2N',
    databaseURL: 'https://card-scanner-d8d50-default-rtdb.firebaseio.com',
  );
}
